// Generated by CoffeeScript 1.6.3
var Player, ground_line, hero, hero_texture;

ground_line = 500;

Player = (function() {
  Player.life = 3;

  function Player(sprite) {
    this.sprite = sprite;
    sprite.anchor.x = 0;
    sprite.anchor.y = 0;
    sprite.position.y = ground_line - sprite.height;
    this.alive = true;
    this.health = 6;
    this.velocity_x = 0;
    this.velocity_y = 0;
    this.direction = 1;
  }

  Player.prototype.flip_sprite = function() {
    this.direction *= -1;
    this.sprite.scale.x *= -1;
    return this;
  };

  Player.prototype.fall = function(dy) {
    if (dy == null) {
      dy = 0;
    }
    if (this.sprite.position.y < ground_line) {
      this.sprite.position.y += 1;
    } else {
      this.sprite.position.y += dy;
    }
    return this;
  };

  Player.prototype.fire_projectile = function(stage) {
    return new Projectile(stage, this.sprite.position.x, this.sprite.position.y);
  };

  Player.prototype.move_character = function(dx, dy) {
    if (dx == null) {
      dx = 0;
    }
    if (dy == null) {
      dy = 0;
    }
    this.sprite.position.x += dx;
    this.fall(dy);
    return this;
  };

  Player.prototype.collision_test_enemy = function(x, y) {
    return (x > this.sprite.position.x && x < this.sprite.position.x + this.sprite.width) && (y > this.sprite.position.y && y < this.sprite.position.y + this.sprite.height);
  };

  Player.prototype.collison_test = function(enemy_list) {
    var enemy, _i, _len;
    if (enemy_list == null) {
      false;
    } else {
      for (_i = 0, _len = enemy_list.length; _i < _len; _i++) {
        enemy = enemy_list[_i];
        if (this.collision_test_enemy(enemy.object.position.x, enemy.object.position.y)) {
          true;
        }
      }
    }
    return false;
  };

  Player.prototype.update = function(enemy_list) {
    var flip;
    if (this.health <= 0) {
      this.alive = false;
    } else {
      console.log(this.health);
      if (this.collison_test(enemy_list)) {
        this.health -= 1;
      }
      flip = (this.direction === -1 && this.velocity_x < 0) || (this.direction === 1 && this.velocity_x > 0);
      if (flip) {
        this.move_character(this.direction * this.sprite.width, 0);
        this.flip_sprite();
      }
      if (!flip) {
        this.move_character(this.velocity_x, this.velocity_y);
      }
      this.velocity_x = 0;
      this.velocity_y = 0;
    }
    return this;
  };

  return Player;

})();

hero_texture = PIXI.Texture.fromImage('static/bunny.png');

hero = new Player(new PIXI.Sprite(hero_texture));
